# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agedir < Formula
  desc "age encryption-based secret file manager"
  homepage "https://github.com/asmz/agedir"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/asmz/agedir/releases/download/v1.0.2/agedir_1.0.2_darwin_amd64.tar.gz"
      sha256 "76b34edd8af8c2bc9e5bdc22bd0b475cc48ec73536d6db7b1135863e9527bf98"

      define_method(:install) do
        bin.install "agedir"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/asmz/agedir/releases/download/v1.0.2/agedir_1.0.2_darwin_arm64.tar.gz"
      sha256 "20f255c8c9cf142101336bc88527c437014e65bb566ff4ecc27655bafd996c19"

      define_method(:install) do
        bin.install "agedir"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/asmz/agedir/releases/download/v1.0.2/agedir_1.0.2_linux_amd64.tar.gz"
      sha256 "14609908098d66588e9bce8a026d0900ab27b049703d99c6b0dfc42432f2dc19"
      define_method(:install) do
        bin.install "agedir"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/asmz/agedir/releases/download/v1.0.2/agedir_1.0.2_linux_arm64.tar.gz"
      sha256 "f4194f38952706e46c55d255a6dcdaf5a4f387fe5187adafb878c9453216ad4d"
      define_method(:install) do
        bin.install "agedir"
      end
    end
  end

  test do
    system "#{bin}/agedir", "--version"
  end
end
