# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agedir < Formula
  desc "age encryption-based secret file manager"
  homepage "https://github.com/asmz/agedir"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/asmz/agedir/releases/download/v1.0.3/agedir_1.0.3_darwin_amd64.tar.gz"
      sha256 "447c6962cf0a94c2e52e8442fe0d728a140d6f6c6c8d2a63686a9cad257245fa"

      define_method(:install) do
        bin.install "agedir"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/asmz/agedir/releases/download/v1.0.3/agedir_1.0.3_darwin_arm64.tar.gz"
      sha256 "04c02da4dd7b114fceb258f3bf39dd3750950eb26ba863dfd809509830494398"

      define_method(:install) do
        bin.install "agedir"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/asmz/agedir/releases/download/v1.0.3/agedir_1.0.3_linux_amd64.tar.gz"
      sha256 "da3ee98e4f34148b239905ef576b14363b5790cc9436711ae7cdb2ef0ccf6244"
      define_method(:install) do
        bin.install "agedir"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/asmz/agedir/releases/download/v1.0.3/agedir_1.0.3_linux_arm64.tar.gz"
      sha256 "9506d669e14668042cb968d80b839626385dfe515b84199a734ed170a5850970"
      define_method(:install) do
        bin.install "agedir"
      end
    end
  end

  test do
    system "#{bin}/agedir", "--version"
  end
end
